### ISSUE TITLE
Auto generated content

### ISSUE THREAD

**Issue by Woestebanaan** [open-imx/imxIconsApi#15]
Hi,
I had trouble with updating the imxIcon library.

Work around:

`hatch env remove default` 
`hatch env create`

Is there a way to force to (re)generate the content any other way?

Gr.

**Comment by Hazedd** [comment]
The workaround you mentioned is indeed a good way to reset the environment:

```bash
hatch env remove default
hatch env create
```

If you'd like to force the regeneration of the environment content without manually removing and recreating it, you can use:

```bash
hatch env prune
hatch env create
```

The hatch env prune command removes all existing environments, ensuring a clean state, and hatch env create will regenerate the default environment.

If I have the time, I will create a new README section aligned with imxInsights. I'll also implement and include details on using the [Hatch version feature](https://hatch.pypa.io/latest/version/) to replace bumpversion, simplifying version management.
