### ISSUE TITLE
[Bug] Url svg returns wrong icon

### ISSUE THREAD

**Issue by Woestebanaan** [open-imx/imxIconsApi#21]
The following address:

https://[imx-icons-api.azurewebsites.net/IMX-v1.2.4/svg/IlluminatedSignNotIntegrated.svg](https://imx-icons-api.azurewebsites.net/IMX-v1.2.4/svg/IlluminatedSignNotIntegrated.svg)

Returns:
![image](https://github.com/user-attachments/assets/3f23b4e8-907f-4ffe-88fa-a13435f94983)

But expects:
![image](https://github.com/user-attachments/assets/69c92b74-d94e-4e69-8c6f-bf4256249f7d)

**Comment by Hazedd** [comment]
solved in latest release
